# Generated by Django 4.2.2 on 2023-07-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainments', '0002_book_author_book_genre_book_publication_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='books/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='movies/'),
        ),
        migrations.AddField(
            model_name='tvseries',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tvseries',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tvseries/'),
        ),
    ]
