# Generated by Django 4.2.2 on 2023-07-07 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entertainments', '0003_book_description_book_image_movie_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='episodes_watched',
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='episodes/')),
                ('description', models.TextField(null=True)),
                ('tvseries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entertainments.tvseries')),
            ],
        ),
        migrations.AddField(
            model_name='progress',
            name='episodes_watched',
            field=models.ManyToManyField(blank=True, to='entertainments.episode'),
        ),
    ]
