# Generated by Django 4.2.2 on 2023-07-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainments', '0004_remove_progress_episodes_watched_episode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='release_date',
            field=models.DateField(null=True),
        ),
    ]
